### ISSUE TITLE
Reaching out with an invite to join the community

### ISSUE THREAD

**Issue by shmup** [bannsec/cosmosocks#1]
I tried shooting you a message from your contact form (on your website), but no matter the browser tested, the Captcha was never loading so I could never satisfy the Human requirements :(

I showed this project to Justine and the Cosmo Discord and we'd love to have ya over to chat about the work you're doing.

If you're interested, here ya go: https://discord.gg/s6Yp7DUj

**Comment by bannsec** [comment]
Hey! For sure :) My website is a bit rundown at the moment lol so not really surprised the form doesn't work anymore.

Looks like the invite link expired?

**Comment by shmup** [comment]
> Looks like the invite link expired?

Oops! Here you go: https://discord.gg/ZnFxUuJu
